module Transpiler
  class 1_0
    # Examples
    # 00 0a 00 00 00 80 // write dimming a 1 device sin ACK valor 80 (127)
    # 00 0a 50 00 01 FF // write dimming al grupo 5000 con ACK id msg 01 prendido 100% (FF)
    # 01 0a 00 00 02         // read dimming de 1 device message id 02
    # 01 0a 02 80        // response valor dimming 80 message id 02

    #VERBS
    AP_VERB_WRITE = 0
    AP_VERB_READ = 1
    AP_VERB_INSERT = 2
    AP_VERB_TRUNCATE = 3
    AP_VERB_COUNT = 4
    AP_VERB_DELETE = 5
    AP_VERB_PING = 6
    AP_VERB_SYNC = 7
    AP_VERB_OTA = 8
    AP_VERB_TEACH_ME = 9
    AP_VERB_TEACH = 10
    AP_VERB_NONE = 255

    def verbs
      {write: AP_VERB_WRITE,
       read: AP_VERB_READ,
       insert: AP_VERB_INSERT,
       truncate: AP_VERB_TRUNCATE,
       count: AP_VERB_COUNT,
       delete: AP_VERB_DELETE,
       ping: AP_VERB_PING,
       sync: AP_VERB_SYNC,
       ota: AP_VERB_OTA,
       teach_me: AP_VERB_TEACH_ME,
       teach: AP_VERB_TEACH,
       none: AP_VERB_NONE }
    end

    #NOUNS
    #AP_NOUN_PASSWORD = 0 #[DEPRECATED]
    #AP_NOUN_LOCATION_ID = 1 #[DEPRECATED]
    #AP_NOUN_DEVICE_ID = 2 #[DEPRECATED]
    AP_NOUN_GROUPS_TABLE = 3
    AP_NOUN_DATE_TIME = 4 #[DEPRECATED]
    #AP_NOUN_GEO_LOCATION = 5 #[DEPRECATED]
    AP_NOUN_SUN_RISE_SET_TABLE = 6
    AP_NOUN_SCHEDULE_TABLE = 7
    #AP_NOUN_AGENDA_TABLE = 8 #[DEPRECATED]
    AP_NOUN_COUNTDOWN = 9
    AP_NOUN_DIMMING = 10
    #AP_NOUN_OTAU_MODE = 11 #[DEPRECATED]
    #AP_NOUN_FLASH_TIMES = 12 #[DEPRECATED]
    #AP_NOUN_FACTORY_RESET = 13 #[DEPRECATED]
    #AP_NOUN_LOCATION_DEVICE_ID = 14 #[DEPRECATED]
    #AP_NOUN_TRIAC_TIME = 15 #[DEPRECATED]
    #AP_NOUN_TRIAC_EXTRA_TIME = 16 #[DEPRECATED]
    #AP_NOUN_DIMMING_TABLE = 17 #[DEPRECATED]
    #AP_NOUN_SYNCHRONIZATION  = 18 #[DEPRECATED]
    #AP_NOUN_FAST_SCHEDULE_TABLE = 19 #[DEPRECATED]
    #AP_NOUN_TARGET_GROUP_TABLE = 20 #[DEPRECATED]
    AP_NOUN_DATE = 21
    AP_NOUN_TIME = 22
    #AP_NOUN_BATTERY = 23 #[DEPRECATED]
    AP_NOUN_TEMPERATURE = 24
    AP_NOUN_FADE_TIME = 25
    AP_NOUN_NONE = 255

    def nouns
      {groups_table: AP_NOUN_GROUPS_TABLE,
      date_time: AP_NOUN_DATE_TIME,
      sun_rise_set_table: AP_NOUN_SUN_RISE_SET_TABLE,
      scheduel_table: AP_NOUN_SCHEDULE_TABLE,
      countdown: AP_NOUN_COUNTDOWN,
      dimming: AP_NOUN_DIMMING,
      date: AP_NOUN_DATE,
      time: AP_NOUN_TIME,
      temperature: AP_NOUN_TEMPERATURE,
      fade_time: AP_NOUN_FADE_TIME,
      none: AP_NOUN_NONE}
    end

    #VENDORS
    APP_VENDOR_ID_AVION = 001
    APP_VENDOR_ID_JASCO = 002
    APP_VENDOR_ID_GE = 003
    APP_VENDOR_ID_DOMITECH = 004
    #APP_VENDOR_ID_AVION_COMMUNITY = 005 #[DEPRECATED]
    APP_VENDOR_ID_BRIDGELUX = 006
    APP_VENDOR_ID_GREEN_POWER_SOLUTIONS = 007

    def vendors
      {avion: APP_VENDOR_ID_AVION,
      jasco: APP_VENDOR_ID_JASCO,
      ge: APP_VENDOR_ID_GE,
      domitech: APP_VENDOR_ID_DOMITECH,
      bridgelux: APP_VENDOR_ID_BRIDGELUX,
      green_power_solutions: APP_VENDOR_ID_GREEN_POWER_SOLUTIONS}
    end

    #APP_VENDOR_ID_AVION
    APP_PRODUCT_ID_AVION_DEV_KIT = 1 #[DEPRECATED]
    APP_PRODUCT_ID_AVION_SWITCH = 2
    #APP_PRODUCT_ID_AVION_ADAPTOR = 3 #[DEPRECATED]
    APP_PRODUCT_ID_AVION_LIGHT_BULB = 4
    APP_PRODUCT_ID_AVION_STARTER_KIT = 5
    APP_PRODUCT_ID_CSR_DEV_KIT = 6

    #APP_VENDOR_ID_JASCO
    APP_PRODUCT_ID_JASCO_OUTDOOR_MODULE = 1
    APP_PRODUCT_ID_JASCO_IN_WALL_SWITCH = 2
    APP_PRODUCT_ID_JASCO_IN_WALL_DIMMER = 3
    APP_PRODUCT_ID_JASCO_OPP_DIMMER = 4
    APP_PRODUCT_ID_JASCO_OPP_RELAY = 5

    #APP_VENDOR_ID_GE
    APP_PRODUCT_ID_GE_ALIGN_BULB = 1

    #APP_VENDOR_ID_DOMITECH
    APP_PRODUCT_ID_DOMITECH_LIGHT_BULB = 1

    #APP_VENDOR_ID_AVION_COMMUNITY
    #APP_PRODUCT_ID_AVION_STARTER_KIT = 1 #[DEPRECATED]

    #APP_VENDOR_ID_BRIDGELUX
    APP_PRODUCT_ID_BRIDGELUX = 1

    #APP_VENDOR_ID_GREEN_POWER_SOLUTIONS
    APP_PRODUCT_ID_GREEN_POWER_SOLUTIONS = 1


  end
end
